### ISSUE TITLE
[Assignment-02] Code Review

### ISSUE THREAD

**Issue by youngkwon02** [LikeLion-at-CAU-10th/Damin-Choi#1]
https://github.com/LikeLion-at-CAU-10th/Damin-Choi/blob/b516d7476eca9bb0c947efa681d31dab09acef9a/assignment/assignment-02/flex2.css#L108-L111

float-basis 속성은 경우에 따라서 width 또는 height의 길이를 설정하기 때문에, 명시적으로 width: ..; height: ..; 라고 써주는게 좋을거 같아~!
예를들어 위에 코드는 다음과 같이 작성하면 더 직관적인 코드가 될거야!

```css
.block10 { 
     width: 38%; 
     height: 98%; 
 } 
```
